name: Update M3U8 File

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour (Change as needed)
  workflow_dispatch:  # Allow manual runs

jobs:
  update-m3u8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Requests
        run: pip install requests

      - name: Run Script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python tonton_tv9.py

      - name: Commit and Push
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "your-github-username"
          git add tv9.m3u8
          git commit -m "Updated TV9.m3u8"
          git push
